// Code generated by protoc-gen-go-ktcp. DO NOT EDIT.
// versions:
// protoc-gen-go-ktcp v0.0.1

package pb

import (
	context "context"
	errors "github.com/go-kratos/kratos/v2/errors"
	ktcp "github.com/kwstars/ktcp"
	packing "github.com/kwstars/ktcp/packing"
)

var _ = new(context.Context)
var _ = new(errors.Error)
var _ = new(ktcp.Server)
var _ = new(packing.Packer)

type UserServiceKTCPServer interface {
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
}

func RegisterUserServiceKTCPServer(s *ktcp.Server, srv UserServiceKTCPServer) {
	s.AddRoute(uint32(ID_ID_LOGIN_REQ), _UserService_Login0_KTCP_Handler(srv))
	s.AddRoute(uint32(ID_ID_CREATE_ROLE_REQ), _UserService_CreateRole0_KTCP_Handler(srv))
}

func _UserService_Login0_KTCP_Handler(srv UserServiceKTCPServer) func(ctx ktcp.Context) error {
	return func(ctx ktcp.Context) error {
		var in LoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			se := errors.FromError(err)
			return ctx.Send(uint32(ID_ID_LOGIN_RESP), packing.ErrType, se)
		}
		reply := out.(*LoginResp)
		return ctx.Send(uint32(ID_ID_LOGIN_RESP), packing.OKType, reply)
	}
}

func _UserService_CreateRole0_KTCP_Handler(srv UserServiceKTCPServer) func(ctx ktcp.Context) error {
	return func(ctx ktcp.Context) error {
		var in CreateRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			se := errors.FromError(err)
			return ctx.Send(uint32(ID_ID_CREATE_ROLE_RESP), packing.ErrType, se)
		}
		reply := out.(*CreateRoleResp)
		return ctx.Send(uint32(ID_ID_CREATE_ROLE_RESP), packing.OKType, reply)
	}
}
